Repository nonlinear-labs-dev/C15, pull requests merged in 2018-03, with the labels that each got.

#102 added smoothing param descriptions
  playground/src/parameters/descriptions/324.txt
  playground/src/parameters/descriptions/325.txt
  playground/src/parameters/descriptions/326.txt
  playground/src/parameters/descriptions/327.txt
Labels: enhancement, good first issue, help wanted, invalid, question

#101 added checkboxes for hw sources return modes
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/PedalContextMenu.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/RibbonContextMenu.java
Labels: enhancement

#119 made fileinfo nicer looking and long paths readable
  playground/src/proxies/hwui/panel-unit/boled/file/FileInfoContent.cpp
  playground/src/proxies/hwui/panel-unit/boled/file/FileInfoContent.h
Labels: bug, code quality

#120 push to the front all HTML Dialogs now, no static Z INdex Neccessary
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/SearchQueryDialog.java
Labels: bug, good first issue

#121 fix highlighting the last used 'rename' entry
  playground/src/proxies/hwui/controls/ButtonMenu.cpp
  playground/src/proxies/hwui/controls/ButtonMenu.h
  playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
  playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h
  playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.cpp
  playground/src/proxies/hwui/panel-unit/boled/parameter-screens/ParameterLayout.h
Labels: bug

#124 fixed parameter layout by replacing a magic number.
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/parameters/BeltParameterLayout.java
Labels: bug, code quality, enhancement

#122 Fixed Bug and finished Feature
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/presets/bank/preset/Preset.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/ContextMenuItem.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/PresetContextMenuItem.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/BeltPreset.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetColorTagContextMenu.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/belt/presets/PresetContextMenu.java
Labels: bug, enhancement

#126 Setup Pedal Rework
  playground/src/proxies/hwui/panel-unit/boled/setup/PedalSelectionControl.cpp
Labels: bug

#127 fixed a strange bug that overriding your own preset skips the rename …
  NonMaps/src/com/nonlinearlabs/NonMaps/client/ServerProxy.java
  playground/src/presets/BankActions.cpp
Labels: bug

#130 Lock WebUI and BOLED rule change
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/LabelModuleHeader.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/maps/parameters/ParameterEditor.java
  playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterEditButtonMenu.cpp
Labels: enhancement

#129 added a systemtime on par with the boled in webui setup
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/setup/SystemDateTimeInfo.java
  NonMaps/src/com/nonlinearlabs/NonMaps/client/world/overlay/setup/SystemInfoPage.java
  playground/src/device-info/DateTimeInfo.cpp
Labels: enhancement

#125 Fix undo compare
  playground/src/presets/PresetManagerActions.cpp
  playground/src/proxies/lpc/LPCParameterChangeSurpressor.h
Labels: bug
